Extend conventions and guidelines
noestit/Noestit.github.io pull request #2
Opened 2021-05-19 15:10 UTC by Cr3ature

- extend with codespaces and docker
- reform github pages 
- reform navigations 
- extend pages

2021-05-19 17:15 UTC, huysentruitw commented on _site/code/index.html
> +<!doctype html>
I would ignore the _site folder and exclude it from the repo, is that possible?

2021-05-28 08:15 UTC, Cr3ature commented on _site/code/index.html
> +<!doctype html>
should be possible in the ignore folder. This is build from within the codespaces. Added in the .gitignore

2021-05-28 13:17 UTC, ThomasVer requested changes

2021-05-28 13:17 UTC, ThomasVer commented on _pages/code/codeconventions/best-practices.md
> +    if(!ModelState.IsValid)
```suggestion
    if (!ModelState.IsValid)
```

2021-05-28 13:17 UTC, ThomasVer commented on _pages/code/codeconventions/best-practices.md
> +    //Code to create user
```suggestion
    // Code to create user
```

2021-05-28 13:17 UTC, ThomasVer commented on _pages/code/codeconventions/pattern-matching.md
> +if(diceRoll is 3){
```suggestion
if (diceRoll is 3)
{
```

2021-05-28 13:17 UTC, ThomasVer commented on _pages/tooling/editorConfig/coding-conventions.md
> +nog wa nieuws
Add actual content

2021-05-28 13:17 UTC, ThomasVer commented on _pages/code/codeguidelines/coding-style.md
> +//Better: string interpolation (${})
```suggestion
// Better: string interpolation (${})
```

2021-05-28 13:17 UTC, ThomasVer commented on _pages/code/codeconventions/pattern-matching.md
> +switch(number)
```suggestion
switch (number)
```

2021-05-28 13:17 UTC, ThomasVer commented on _pages/code/codeconventions/pattern-matching.md
> +switch(shape)
```suggestion
switch (shape)
```

2021-05-28 13:38 UTC, Cr3ature commented on CONDUCT.md
> +
resolved in new commit

2021-05-28 13:39 UTC, Cr3ature commented on _pages/code/codeconventions/addition-to-conventions.md
> +//As operator
Resolved in new commit

2021-05-28 13:40 UTC, Cr3ature commented on _pages/code/codeconventions/best-practices.md
> +    if(!ModelState.IsValid)
Resolved in next commit

2021-05-28 13:40 UTC, Cr3ature commented on _pages/code/codeconventions/best-practices.md
> +        //Code to handle invalid form
Resolved in next commit

2021-05-28 13:41 UTC, Cr3ature commented on _pages/code/codeconventions/best-practices.md
> +    //Code to create user
Resolved in next commit

2021-05-28 14:31 UTC, ThomasVer submitted a review, later dismissed

2021-05-28 14:42 UTC, merged